name: uconext

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: uconext_development
      POSTGRES_PASSWORD: uconext_development
      POSTGRES_USER: uconext_development
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
